name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          python-version: 3.6
      - run: echo "The workflow is now ready to test the code on the runner."
      - name: List files in the repository
        run: |
          python -m pip install --upgrade pip
          pip install pep8 
          cd ${{ github.workspace }}/projects/Currency_converter/ && pep8 cc.py 
